Carpooling/Carpooling/Models/UserViewModel.cs
namespace Carpooling.Web.Models
{
    public class UserViewModel
    {
        public int Id { get; set; }

        public string Username { get; set; }

        public string Email { get; set; }

        public string PhoneNumber { get; set; }

        public string Status { get; set; }
    }
}

Carpooling/Carpooling/Controllers/APIController/UsersController.cs
using Carpooling.Services.Services.Contracts;
using Carpooling.Web.Helpers.Contracts;
using Carpooling.Web.Models.APIModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace Carpooling.Web.Controllers.APIController
{
    [ApiController]
    [Route("api/[controller]")]
    public class UsersController : Controller
    {
        private readonly IUserService userService;
        private readonly IAuthHelper authHelper;

        public UsersController(IUserService userService, IAuthHelper authHelper)
        {
            this.userService = userService;
            this.authHelper = authHelper;
        }

        [HttpGet("{id}")]
        public IActionResult Get([FromHeader] string userName, [FromHeader] string password, int id)
        {
            try
            {
                var user = this.authHelper.TryGetUser(userName, password);
                if (user.Roles.Any(role => role == "User" && user.Id == id))
                {
                    var logedUser = this.userService.Get(id);
                    var result = logedUser.UserResponseModel();
                    return Ok(result);
                }
                return BadRequest();
            }
            catch (ArgumentException e)
            {
                return this.NotFound(e);
            }
        }

        [HttpGet("")]
        public ActionResult GetUsers([FromHeader] string credentials, [FromHeader] string password)
        {
            try
            {
                var employee = this.authHelper.TryGetUser(credentials, password);
                if (employee.Roles.Any(role => role == "Admin"))
                {
                    var result = this.userService.GetAll().Select(user => user.UserResponseModel());
                    return this.Ok(result);
                }

                return this.BadRequest();
            }
            catch (ArgumentException e)
            {
                return this.NotFound(e);
            }
        }

        [HttpPost("")]
        public IActionResult CreateUser([FromBody] UserRequestModel userRequestModel)//
        {
            try
            {
                var user = userRequestModel.UserRequestModel();
                var result = this.userService.Create(user).UserResponseModel();
                return this.Created("New Customer", result);
            }
            catch (ArgumentNullException)
            {
                return this.BadRequest();
            }
        }

        [HttpPut("{id}")]
        public IActionResult UpdateUser([FromHeader] string credentials, [FromHeader] string password, [FromBody] UserRequestModel userRequestModel, int userId)
        {
            try
            {
                var user = this.authHelper.TryGetUser(credentials, password);
                if (user.Roles.Any(role => role == "User" && user.Id == userId))
                {
                    var userToBeModified = userRequestModel.UserRequestModel();
                    var updatedUser = this.userService.Update(userId, userToBeModified);
                    var result = updatedUser.UserResponseModel();
                    return this.Ok(result);
                }

                return this.BadRequest();
            }
            catch (ArgumentException e)
            {
                return this.NotFound(e);
            }
        }

        [HttpDelete("{id}")]
        public IActionResult DeleteUser([FromHeader] string userName, [FromHeader] string password, int id)
        {
            try
            {
                var user = this.authHelper.TryGetUser(userName, password);
                if (user.Roles.Any(role => role == "Admin" && user.Id == id))
                {
                    this.userService.Delete(id);
                    return this.NoContent();
                }
                return BadRequest();
            }
            catch (ArgumentException e)
            {
                return this.NotFound(e);
            }
        }

        [HttpPut("{userId}/Block")]
        public IActionResult BlockUser([FromHeader] string userName, [FromHeader] string password, int userId)
        {
            try
            {
                var user = this.authHelper.TryGetUser(userName, password);
                if (user.Roles.Contains("Admin") && user.Id != userId && !this.userService.Get(userId).Roles.Contains("Admin"))
                {
                    this.userService.BlockUser(userId);
                    return this.Ok();
                }
                return this.BadRequest();
            }
            catch (ArgumentException e)
            {
                return this.NotFound(e);
            }
        }

        [HttpPut("{userId}/Unblock")]
        public IActionResult UnblockUser([FromHeader] string userName, [FromHeader] string password, int userId)
        {
            try
            {
                var user = this.authHelper.TryGetUser(userName, password);
                if (user.Roles.Contains("Admin") && user.Id != userId && !this.userService.Get(userId).Roles.Contains("Admin"))
                {
                    this.userService.UnblockUser(userId);
                    return this.Ok();
                }
                return this.BadRequest();
            }
            catch (ArgumentException e)
            {
                return this.NotFound(e);
            }
        }

        [HttpGet("Search")]
        public IActionResult SearchAsAdmin([FromHeader] string userName, [FromHeader] string password, string phoneNumber, string usersName, string email)
        {
            try
            {
                var user = this.authHelper.TryGetUser(userName, password);
                if (user.Roles.Any(role => role == "Admin"))
                {
                    var sortedUsers = this.userService.GetFilteredUsers(email, phoneNumber, usersName).Select(user => user.UserResponseModel());
                    return this.Ok(sortedUsers);
                }
                return BadRequest();
            }
            catch (ArgumentException e)
            {
                return this.NotFound(e);
            }
        }

    }
}

Carpooling/Carpooling/Controllers/FeedbacksController.cs
using Carpooling.Services.Services.Contracts;
using Carpooling.Web.Helpers;
using Carpooling.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Carpooling.Web.Controllers
{
    [AuthorizationAttribute(Role = "User")]
    public class FeedbacksController : Controller
    {
        private readonly IFeedbackService feedbackService;
        private readonly ITravelService travelService;

        public FeedbacksController(IFeedbackService feedbackService, ITravelService travelService)
        {
            this.feedbackService = feedbackService;
            this.travelService = travelService;
        }

        public IActionResult Received(int id, string username, double? rating, bool ratingSort)
        {
            ViewData["VisitedFeedbacksUserId"] = id;

            var feedbacks = this.feedbackService.SearchUserRecievedFeedbacks(id, username, rating, ratingSort);
            var searchResult = feedbacks.Select(feedback => feedback.ToFeedbackReceivedViewModel());
            return View(searchResult);
        }

        public IActionResult Given(int id, string username, double? rating, bool ratingSort)
        {
            ViewData["VisitedFeedbacksUserId"] = id;

            var feedbacks = this.feedbackService.SearchUserGivenFeedbacks(id, username, rating, ratingSort);
            var searchResult = feedbacks.Select(feedback => feedback.ToFeedbackGivenViewModel());
            return View(searchResult);
        }

        public IActionResult Create(int id, int travelId)
        {
            ViewData["Travel"] = travelId;
            ViewData["UserTo"] = id;
            var feedbackCreate = new FeedbackCreateViewModel();
            return View(feedbackCreate);
        }

        [HttpPost]
        public IActionResult Create(FeedbackCreateViewModel feedbackCreateViewModel, int userToId, int travelId)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(feedbackCreateViewModel);
            }

            var userFromId = int.Parse(this.HttpContext.Session.GetString("UserId"));
            var travel = this.travelService.Get(travelId);
            var feedback = feedbackCreateViewModel.ToFeedbackCreateDTO();
            feedback.UserFromId = userFromId;
            feedback.TravelId = travelId;
            feedback.UserToId = userToId;
            if (travel.Driver.Id == userFromId)
            {
                feedback.Type = Data.Models.Enums.FeedbackType.Driver;
            }
            else
            {
                feedback.Type = Data.Models.Enums.FeedbackType.Passenger;
            }

            this.feedbackService.Create(feedback);
            return RedirectToAction("Participants", "MyTravels", new { id = travelId });
        }
    }
}

Carpooling/Carpooling/Controllers/UsersController.cs
using Carpooling.Services.Services.Contracts;
using Carpooling.Web.Helpers;
using Carpooling.Web.Helpers.Contracts;
using Carpooling.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;

namespace Carpooling.Web.Controllers
{
    [AuthorizationAttribute(Role = "User")]
    public class UsersController : Controller
    {
        private readonly IUserService userService;
        private readonly IImageHelper imageHelper;

        public UsersController(IUserService userService, IImageHelper imageHelper)
        {
            this.userService = userService;
            this.imageHelper = imageHelper;
        }

        public IActionResult MyProfile(int id)
        {
            var user = this.userService.Get(id).ToUserProfileViewModel();
            return View(user);
        }

        public IActionResult Update(int id)
        {
            var user = this.userService.Get(id).ToUserUpdateViewModel();
            return View(user);
        }

        [HttpPost]
        public IActionResult Update(UserUpdateViewModel userUpdateViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(userUpdateViewModel);
            }

            string password = userUpdateViewModel.Password;
            if (password != null && !Regex.IsMatch(password, @"^.*(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!*@#$%^&+=-]).*$"))
            {
                this.ModelState.AddModelError("PasswordError",
                    "Password must be at least 8 characters long and must contain at least one capital letter, one digit and one special symbol like ( !, *, @, #, $, %, ^, &, +, =, - )");
                return this.View(userUpdateViewModel);
            }

            string profilePicture = string.Empty;
            if (userUpdateViewModel.ProfilePicture != null)
            {
                profilePicture = this.imageHelper.UploadImage(userUpdateViewModel.ProfilePicture);
                this.HttpContext.Session.SetString("ProfilePicture", profilePicture);
            }

            var user = userUpdateViewModel.ToUserUpdate(profilePicture);
            var userId = int.Parse(this.HttpContext.Session.GetString("UserId"));
            this.userService.Update(userId, user);
            return this.RedirectToAction("MyProfile", "Users", new { id = userId });
        }
    }
}

Carpooling/Carpooling/Views/Users/MyProfile.cshtml
@{ 
    ViewData["Title"] = "My profile";
    this.ViewData["CurrentUser"] = this.Context.Session.GetString("CurrentUser");
}
@model Carpooling.Web.Models.UserProfileViewModel

<div class="row gutters-sm">
    <div class="col-md-4 mb-3">
        <div class="card">
            <div class="card-body">
                <div class="d-flex flex-column align-items-center text-center">
                    <img src="~/images/@Model.ProfilePicture" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                        <p class="text-secondary mb-1">Rating as Driver: @Model.RatingAsDriver</p>
                        <p class="text-muted font-size-sm">Rating as passenger: @Model.RatingAsPassenger</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="card mb-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        @Model.FirstName @Model.LastName
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        @Model.Email
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Phone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        @Model.PhoneNumber
                    </div>
                </div>
                <hr>
                <div class="row">
                    @if (ViewData["CurrentUser"].Equals(Model.Username))
                    {
                        <div class="col-sm-auto">
                            <a class="btn btn-info " asp-controller="Users" asp-action="Update" asp-route-id="@Model.Id">Edit</a>
                        </div>
                    }

                    @if (ViewData["CurrentUser"].Equals(Model.Username))
                    {
                        <div class="col-sm-auto">
                            <a class="btn btn-info " asp-controller="Feedbacks" asp-action="Given" asp-route-id="@Model.Id">Given feedbacks</a>
                        </div>
                    }
                    <div class="col-sm-auto">
                        <a class="btn btn-info " asp-controller="Feedbacks" asp-action="Received" asp-route-id="@Model.Id">Recieved </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Carpooling/Carpooling/Views/Users/Update.cshtml
@{
    ViewData["Title"] = "Update profile";
}
@model Carpooling.Web.Models.UserUpdateViewModel

<div class="container">
    <form asp-action="Update" method="post" enctype="multipart/form-data">
        <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Edit your profile</h5>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="ProfilePicture" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="ProfilePicture" class="custom-file-input form-control" id="customFile" name="ProfilePicture">
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Password"></label>
                <input class="form-control" type="password" asp-for="Password" name="Password" value="@Model.Password" />
                <span></span>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Email"></label>
                <input class="form-control" type="email" asp-for="Email" name="Email" value="@Model.Email" />
                <span asp-validation-for="Email"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="PhoneNumber"></label>
                <input class="form-control" type="number" asp-for="PhoneNumber" name="PhoneNumber" value="@Model.PhoneNumber" />
                <span asp-validation-for="PhoneNumber"></span>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="FirstName"></label>
                <input class="form-control" type="text" asp-for="FirstName" name="FirstName" value="@Model.FirstName" />
                <span asp-validation-for="FirstName"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="LastName"></label>
                <input class="form-control" type="text" asp-for="LastName" name="LastName" value="@Model.LastName" />
                <span asp-validation-for="LastName"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Save changes</button>
    </form>
</div>

@section scripts{
    <script type="text/javascript">
  $(".custom-file-input").on("change", function () {
   var fileName = $(this).val().split("\\").pop();
   $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
  });
    </script>
}